/*
 * weather6.sql
 * Copyright (C) 2016-04-20 12:49 coconor <coconor@umich.edu>
 *
 */



SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE '%a' OR CITY LIKE '%e' OR CITY LIKE '%i' OR CITY LIKE '%u' OR CITY LIKE '%o'; 

SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'a%' OR CITY LIKE 'e%' OR CITY LIKE 'i%' OR CITY LIKE 'u%' OR CITY LIKE 'o%'; 


SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'a%a' OR CITY LIKE 'e%e' OR CITY LIKE 'i%i' OR CITY LIKE 'u%u' OR CITY LIKE 'o%o'; 
